### ISSUE TITLE
Make tabs reorderable

### ISSUE THREAD

**Issue by AngelFireOmega** [NightmareXIV/DynamicBridge#11]
Characters tab should be in front of Profiles.

- Characters use Profies
- Profiles use Rules
- Rules use Presets

**Comment by Limiana** [comment]
But for character to use a profile, that profile needs to be created first though

**Comment by AngelFireOmega** [comment]
I think the correct sequence from top to bottom is:
1. Characters
2. Profiles
3. Rules
4. Presets

It's just easier for the users to understand the relationship if you put the tabs in the same or reverse order.
I am a professional test engineer for almost 20 years and current tab order still take me several minutes to figure out how to impliment the correct setting.

**Comment by PrincessRTFM** [comment]
I disagree. I think it would make more sense to put rules, presets, global presets, and layered designs first, _then_ profiles and characters. My reasoning is thus:

- If you want to change when a look is used, you'll need to modify the rules.
- If you want to tweak a particular look, you need to edit the preset/design.
- If you want to add a whole _new_ look, you need to make a preset and/or layered design for it, _and_ add a new rule to control its use.
- You only need to set up a new profile once per profile, and likewise for a new character.
- If you only play a single character, you'll never need either tab again.
- You're more likely to need to refer to housing registration than to characters and profiles, in the event that you move or change FCs.

At the front of the tab bar, the most commonly used tabs; at the end, the least common. It makes little sense to me to put the tabs you're most likely to use once and never again at the very front. To that end, I would prefer an ordering like so:

- Dynamic Rules
- Layered Designs
- [Global] Presets (in either order)
- House Registration
- Characters and Profiles (in either order)

This would not only place the more commonly used tabs at the front, it would also maintain your logic, albeit in reverse order.

----

Failing the above, I do still feel that the current order is inconsistent with your logic. As you said, you need to make a profile before a character can use it. But then you have the rules _before_ the presets and layered designs, and you need to make those before rules can reference them. If you want to maintain that logic, I would argue a more consistent ordering might be:

- Profiles
- Characters
- [Global] Presets (in either order)
- Layered Designs (since they rely on presets)
- House Registration (since houses must be registered before rules can refer to them)
- Dynamic Rules

**Comment by AngelFireOmega** [comment]
The current design reminds me commercial SSO service and not easy to be understand for standard users. As long as you think it through and have proper documentation, it should be fine.

**Comment by Limiana** [comment]
@AsunaTsuki will take additional look at the design later next week

**Comment by Limiana** [comment]
Reorderable tabs will be the ultimate solution
