### ISSUE TITLE
Consideration: Moodles compatibility?

### ISSUE THREAD

**Issue by PrincessRTFM** [NightmareXIV/DynamicBridge#8]
Dynamic Bridge already supports Honorific, which handles custom titles rather than simply visual appearance. Are there any plans for compatibility with [Moodles](https://github.com/kawaii/Moodles), which allows custom status effects (buffs, debuffs, and specials) with arbitrary values? Mare Synchronos already has compatibility for it and will sync such statuses to paired users, but it might be neat if, for instance, people could automatically set statuses like "Napping" while they're in an estate and using one of the sleeping pose emotes.

**Comment by Goetia-Valefar** [comment]
Is there a way for us to get an option to completely disable our rules so that we can add or remove Honorific titles because as of right now if I want to do that I have to disable all of my rules and then do what I need in Honorific then re-enable my rules? I know it's not something done often but it might be nice to have the option to do like we can with penumbra and all of the mods.
